### ISSUE TITLE
Compatibility with Elytra Trinket

### ISSUE THREAD

**Issue by Nachtalb** [adriantodt/Winged#30]
I have installed this mod https://www.curseforge.com/minecraft/mc-mods/elytra-trinket-fabric. I haven't found the items yet to craft winged wings, so I am still wearing the default elytra. 
While the default Minecraft elytra is equipped in the default chest plate slot it works just fine. But when it is in the trinket slot added by the mod linked above it doesn't work anymore. While starting to glide the animation bugs out a bit and I simply fall to the ground.

https://user-images.githubusercontent.com/9467802/121730287-c372b080-caef-11eb-9026-ec8bd03741c1.mp4

**Comment by NotJustAnna** [comment]
Uninstall Elytra Trinket Fabric and install this: https://www.curseforge.com/minecraft/mc-mods/ffl-trinkets-compat

**Comment by Nachtalb** [comment]
Ahh nice, I'll try that 👍
