### ISSUE TITLE
Opening Zephyr workbench crashes fabric mutiplayer server 

### ISSUE THREAD

**Issue by angrovar** [adriantodt/Winged#36]
Hope this crash report will help you patch this bug.
[crash-2021-07-24_02.21.05-server.txt](https://github.com/CafeteriaGuild/Winged/files/6870201/crash-2021-07-24_02.21.05-server.txt)

**Comment by GabrielOlvH** [comment]
Thanks for reporting, this is fixed as of 3.0.0 which will be available on CurseForge shortly.
