### ISSUE TITLE
Unbreaking does not affect the creative flight duration of a Heart of the Sky.

### ISSUE THREAD

**Issue by James103** [adriantodt/Winged#4]
When using the modpack All of Fabric 3 1.5.3 (Winged Mod 1.16-1.2 for MC 1.16), when you enchant a Heart of the Sky with Unbreaking III using commands or an anvil (both work), you don't get an increased flight duration. The base flight timer is 26 minutes and 40 seconds (1600 seconds), and since the Heart of the Sky has a durability, you would expect that Unbreaking should increase this flight duration allowing you to fly longer.

For example:
Heart of the Sky (no unbreaking): 1600 seconds of flight
Heart of the Sky (Unbreaking III): Expected 6400 seconds of flight, but actually still 1600 seconds.

**Comment by James103** [comment]
Note that this also applies for flight Boosters as well as the Forward Launcher from the same mod. The probability of the Unbreaking effect having no effect on durability until it breaks is 1 / (4^128), or a 1 in 1.15e77 chance, and even higher for the boosters.

**Comment by adriantodt** [comment]
This is intended behaviour, I'm not coding "Unbreaking" behaviour into those items.
