### ISSUE TITLE
heart of the sky disabled

### ISSUE THREAD

**Issue by Boporus** [adriantodt/Winged#42]
A few friends and I are currently playing on a Minecraft server with the modpack all the mods 4 and we noticed that the heart of the sky is disabled or atleast we think it is. I was hoping you could tell me how to enable it.

Yours sincerely Me, the idiot

**Comment by NotJustAnna** [comment]
I have no idea either, never played with AOF4. You're better off asking in the AOF support server. Closing this issue.

In the future, I pretend to split Winged's Creative Flight into another mod.
