### ISSUE TITLE
No loottable for Heart of the Sky!

### ISSUE THREAD

**Issue by KartoffelBreP** [adriantodt/Winged#48]
Hello.
I am playing on a server with friends and we noticed that there is no way to get creative flight wings.
for demonstration i took a screenshot of the loottable class in which i find no loottable for the Heart of the Sky.
Please explain.

![image](https://user-images.githubusercontent.com/86446760/176563509-d5bc3fe6-53f1-48a4-84f6-a4b6b7dc2df0.png)

**Comment by NotJustAnna** [comment]
Loot tables don't work for the Ender Dragon, therefore it's not implemented as a loot table.
