### ISSUE TITLE
Boosters disenchant themselves when they are activated or deactivated.

### ISSUE THREAD

**Issue by James103** [adriantodt/Winged#5]
When using the modpack All of Fabric 1.5.3 (Winged Mod 1.16-1.2 for MC 1.16), when you enchant a Booster from the mod with the Unbreaking and Mending enchantments, the enchantments get removed once you activate or deactivate the booster, meaning that you have to re-enchant the booster with Mending every time you want to refuel it with XP.

**Comment by adriantodt** [comment]
Boosters replace themselves for their active counterparts. Disenchanting is a side-effect. Boosters aren't meant to be refueled with XP.
