### ISSUE TITLE
How to add compatibility with your mod

### ISSUE THREAD

**Issue by ricksouth** [adriantodt/Winged#50]
Hi!

I'd love to make your mod compatible with [Easy Elytra Takeoff](https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff). How can I check if the player has wings equiped? I'd prefer it if there was an option without adding a dependency in the build.gradle.

For adding compatibility with Colytra in Forge, I check for attributes on the player, via:
```
			Collection<AttributeInstance> atrb = player.getAttributes().getSyncableAttributes();
			for (AttributeInstance ai : atrb) {
				for (AttributeModifier m : ai.getModifiers()) {
					String name = m.getName().toLowerCase();
```

Would something like this be possible? Otherwise please let me know :)

**Comment by ricksouth** [comment]
https://github.com/ricksouth/serilum-mc-mods/issues/245 for reference

**Comment by NotJustAnna** [comment]
I don't know if you need to know about Winged specifically but since we use [EntityElytraEvents#CUSTOM](https://maven.fabricmc.net/docs/fabric-api-0.49.4+1.19/net/fabricmc/fabric/api/entity/event/v1/EntityElytraEvents.html#CUSTOM) I guess you could just generalize your code to use this instead?

**Comment by ricksouth** [comment]
I did not know that existed! I'll take a look and let you know, thanks 😄

**Comment by NotJustAnna** [comment]
It was recently added in a collab between Technic1an and me to turn FFL from a user-library to a core Fabric API

**Comment by ricksouth** [comment]
Appreciate it! Added support via `boolean foundelytra = EntityElytraEvents.CUSTOM.invoker().useCustomElytra(player, false);`
